name: facerec-app
channels:
  - conda-forge
dependencies:
  - python=3.9  # Ensure compatibility
  - streamlit
  - dlib
  - face_recognition
  - opencv
  - numpy
  - pillow
  - pip
  - pip:
      - cmake
      - face_recognition
